# Generated by Django 4.2.27 on 2026-01-31 11:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=15, verbose_name='Telefone')),
                ('assunto', models.CharField(max_length=200, verbose_name='Assunto')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
                ('lido', models.BooleanField(default=False, verbose_name='Lido')),
                ('respondido', models.BooleanField(default=False, verbose_name='Respondido')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('culto', 'Culto'), ('conferencia', 'Conferência'), ('retiro', 'Retiro'), ('encontro', 'Encontro'), ('workshop', 'Workshop'), ('celula', 'Célula'), ('outro', 'Outro')], default='culto', max_length=20, verbose_name='Tipo de Evento')),
                ('data_inicio', models.DateTimeField(verbose_name='Data e Hora de Início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora de Término')),
                ('local', models.CharField(max_length=300, verbose_name='Local')),
                ('endereco', models.TextField(blank=True, verbose_name='Endereço Completo')),
                ('vagas', models.PositiveIntegerField(blank=True, help_text='Deixe em branco para vagas ilimitadas', null=True, verbose_name='Número de Vagas')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='eventos/', verbose_name='Imagem do Evento')),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('em_andamento', 'Em Andamento'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='agendado', max_length=20, verbose_name='Status')),
                ('destaque', models.BooleanField(default=False, help_text='Marque para exibir na página inicial', verbose_name='Evento em Destaque')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Formato: (XX) XXXXX-XXXX', regex='^\\(\\d{2}\\)\\s?\\d{4,5}-?\\d{4}$')], verbose_name='Telefone')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo')),
                ('endereco', models.TextField(blank=True, verbose_name='Endereço')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('visitante', 'Visitante')], default='visitante', max_length=20, verbose_name='Status')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='membros/', verbose_name='Foto')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Membros',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Inscrição')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('lista_espera', 'Lista de Espera')], default='pendente', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('presente', models.BooleanField(default=False, verbose_name='Presença Confirmada')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='eventos.evento', verbose_name='Evento')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='eventos.membro', verbose_name='Membro')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'ordering': ['-data_inscricao'],
                'unique_together': {('membro', 'evento')},
            },
        ),
    ]
