# Generated by Django 4.2.27 on 2026-01-31 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='inscricao_fim',
            field=models.DateTimeField(blank=True, help_text='Data e hora de encerramento das inscrições', null=True, verbose_name='Fim das Inscrições'),
        ),
        migrations.AddField(
            model_name='evento',
            name='inscricao_inicio',
            field=models.DateTimeField(blank=True, help_text='Data e hora de abertura das inscrições', null=True, verbose_name='Início das Inscrições'),
        ),
    ]
