# Generated by Django 4.2.27 on 2026-01-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_evento_inscricao_fim_evento_inscricao_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='evento_pago',
            field=models.BooleanField(default=False, help_text='Marque se este evento possui taxa de inscrição', verbose_name='Evento Pago'),
        ),
        migrations.AddField(
            model_name='evento',
            name='valor_inscricao',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor em R$ (deixe em branco para eventos gratuitos)', max_digits=10, null=True, verbose_name='Valor da Inscrição'),
        ),
    ]
