# Generated by Django 4.2.27 on 2026-01-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_participante_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_igreja', models.CharField(default='Champions Church', max_length=200, verbose_name='Nome da Igreja')),
                ('slogan', models.CharField(blank=True, help_text='Frase curta que aparece junto ao nome', max_length=300, verbose_name='Slogan')),
                ('descricao', models.TextField(blank=True, help_text='Texto sobre a igreja para o rodapé', verbose_name='Descrição')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='configuracoes/', verbose_name='Logo')),
                ('logo_branco', models.ImageField(blank=True, null=True, upload_to='configuracoes/', verbose_name='Logo Branco (para fundos escuros)')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='configuracoes/', verbose_name='Favicon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail de Contato')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('whatsapp', models.CharField(blank=True, help_text='Número com DDD (apenas números)', max_length=20, verbose_name='WhatsApp')),
                ('endereco', models.CharField(blank=True, max_length=300, verbose_name='Endereço')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name='Estado (UF)')),
                ('cep', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('facebook', models.URLField(blank=True, help_text='URL completa do perfil/página', verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, help_text='URL completa do perfil', verbose_name='Instagram')),
                ('youtube', models.URLField(blank=True, help_text='URL completa do canal', verbose_name='YouTube')),
                ('tiktok', models.URLField(blank=True, help_text='URL completa do perfil', verbose_name='TikTok')),
                ('twitter', models.URLField(blank=True, help_text='URL completa do perfil', verbose_name='Twitter/X')),
                ('horarios', models.TextField(blank=True, help_text='Ex: Domingos: 9h e 18h | Quartas: 19h30', verbose_name='Horários dos Cultos')),
                ('google_maps_embed', models.TextField(blank=True, help_text='Cole o código iframe do Google Maps', verbose_name='Código embed do Google Maps')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
    ]
