# Generated by Django 4.2.27 on 2026-01-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_configuracao_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='webhook_ativo',
            field=models.BooleanField(default=False, help_text='Marque para ativar o envio de webhooks', verbose_name='Webhook Ativo'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='webhook_inscricao',
            field=models.URLField(blank=True, help_text='URL para enviar dados quando uma nova inscrição é realizada (ex: integração com WhatsApp)', verbose_name='Webhook de Inscrição'),
        ),
    ]
