# Generated by Django 4.2.27 on 2026-01-31 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_webhook_inscricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='is_acompanhante',
            field=models.BooleanField(default=False, help_text='Indica se esta inscrição é de um acompanhante', verbose_name='É Acompanhante'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='responsavel',
            field=models.ForeignKey(blank=True, help_text='Membro responsável por esta inscrição (para acompanhantes)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes_responsavel', to='eventos.membro', verbose_name='Responsável'),
        ),
    ]
