# Generated by Django 4.2.11 on 2026-01-31 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_inscricao_acompanhantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Adulto, Criança (até 12 anos), Adolescente (até 16 anos)', max_length=100, verbose_name='Nome da Categoria')),
                ('descricao', models.CharField(blank=True, help_text='Descrição opcional da categoria', max_length=300, verbose_name='Descrição')),
                ('tipo_valor', models.CharField(choices=[('fixo', 'Valor Fixo'), ('porcentagem', 'Porcentagem do Valor')], default='porcentagem', help_text='Define se o valor é fixo ou uma porcentagem do valor do evento', max_length=20, verbose_name='Tipo de Valor')),
                ('valor', models.DecimalField(decimal_places=2, default=100, help_text='Valor fixo em R$ ou porcentagem (0-100). Ex: 50 = R$50 ou 50%', max_digits=10, verbose_name='Valor')),
                ('idade_minima', models.PositiveIntegerField(blank=True, help_text='Idade mínima para esta categoria (opcional)', null=True, verbose_name='Idade Mínima')),
                ('idade_maxima', models.PositiveIntegerField(blank=True, help_text='Idade máxima para esta categoria (opcional)', null=True, verbose_name='Idade Máxima')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem para exibição na lista (menor = primeiro)', verbose_name='Ordem de Exibição')),
                ('ativo', models.BooleanField(default=True, help_text='Categorias inativas não aparecem no formulário de inscrição', verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Categoria de Participante',
                'verbose_name_plural': 'Categorias de Participantes',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='inscricao',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='status_pagamento',
            field=models.CharField(choices=[('nao_aplicavel', 'Não Aplicável'), ('pendente', 'Pendente'), ('pago', 'Pago'), ('isento', 'Isento')], default='nao_aplicavel', max_length=20, verbose_name='Status do Pagamento'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='valor_inscricao',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor calculado para esta inscrição específica', max_digits=10, verbose_name='Valor da Inscrição'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Categoria do participante (Adulto, Criança, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscricoes', to='eventos.categoriaparticipante', verbose_name='Categoria'),
        ),
    ]
