# Generated by Django 4.2.11 on 2026-01-31 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_categorias_participantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='is_acompanhante',
            field=models.BooleanField(default=False, help_text='Indica se este membro é acompanhante de outro', verbose_name='É Acompanhante'),
        ),
        migrations.AddField(
            model_name='membro',
            name='responsavel',
            field=models.ForeignKey(blank=True, help_text='Membro responsável por este acompanhante', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acompanhantes', to='eventos.membro', verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='telefone',
            field=models.CharField(blank=True, help_text='Número usado para login e receber mensagens', max_length=20, null=True, verbose_name='Telefone/WhatsApp'),
        ),
    ]
