# Generated by Django 4.2.11 on 2026-01-31 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_add_acompanhante_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, help_text='Código único para integração com gateway de pagamento', max_length=36, unique=True, verbose_name='Código da Cobrança')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Cobrança')),
                ('descricao', models.TextField(blank=True, help_text='Detalhes dos itens incluídos nesta cobrança', verbose_name='Descrição')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado'), ('isento', 'Isento'), ('reembolsado', 'Reembolsado')], default='pendente', max_length=20, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_pagamento', models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('referencia_externa', models.CharField(blank=True, help_text='ID da transação no gateway de pagamento', max_length=100, verbose_name='Referência Externa')),
                ('metodo_pagamento', models.CharField(blank=True, help_text='Ex: PIX, Cartão de Crédito, etc.', max_length=50, verbose_name='Método de Pagamento')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobrancas', to='eventos.evento', verbose_name='Evento')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobrancas', to='eventos.membro', verbose_name='Membro Responsável')),
            ],
            options={
                'verbose_name': 'Cobrança',
                'verbose_name_plural': 'Cobranças',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='CobrancaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Item')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
                ('cobranca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='eventos.cobranca', verbose_name='Cobrança')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_cobranca', to='eventos.inscricao', verbose_name='Inscrição')),
            ],
            options={
                'verbose_name': 'Item de Cobrança',
                'verbose_name_plural': 'Itens de Cobrança',
            },
        ),
    ]
