# Generated by Django 4.2.11 on 2026-01-31 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0011_add_cobranca_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='mp_access_token_production',
            field=models.CharField(blank=True, help_text='Token de acesso do Mercado Pago para produção', max_length=100, verbose_name='Access Token (Produção)'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='mp_access_token_sandbox',
            field=models.CharField(blank=True, help_text='Token de acesso do Mercado Pago para ambiente de testes', max_length=100, verbose_name='Access Token (Sandbox)'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='mp_ambiente',
            field=models.CharField(choices=[('sandbox', 'Sandbox (Testes)'), ('production', 'Produção')], default='sandbox', help_text='Selecione o ambiente de operação', max_length=20, verbose_name='Ambiente Mercado Pago'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='mp_ativo',
            field=models.BooleanField(default=False, help_text='Ativar integração com Mercado Pago para pagamentos', verbose_name='Mercado Pago Ativo'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='mp_public_key_production',
            field=models.CharField(blank=True, help_text='Chave pública do Mercado Pago para produção', max_length=100, verbose_name='Public Key (Produção)'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='mp_public_key_sandbox',
            field=models.CharField(blank=True, help_text='Chave pública do Mercado Pago para ambiente de testes', max_length=100, verbose_name='Public Key (Sandbox)'),
        ),
    ]
