# Generated by Django 4.2.27 on 2026-02-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_add_mercadopago_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='webhook_reset_senha',
            field=models.URLField(blank=True, help_text='URL para enviar dados quando um participante solicita reset de senha', null=True, verbose_name='Webhook de Reset de Senha'),
        ),
    ]
