# Generated by Django 4.2.11 on 2026-02-05 13:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0013_configuracaosite_webhook_reset_senha'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissaoMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único do menu (ex: eventos, membros, inscricoes)', max_length=50, unique=True, verbose_name='Código')),
                ('nome', models.CharField(help_text='Nome exibido do menu (ex: Eventos, Membros, Inscrições)', max_length=100, verbose_name='Nome do Menu')),
                ('descricao', models.TextField(blank=True, help_text='Descrição opcional da funcionalidade do menu', verbose_name='Descrição')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição do menu (menor = primeiro)', verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, help_text='Se inativo, o menu não aparecerá para nenhum grupo', verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Permissão de Menu',
                'verbose_name_plural': 'Permissões de Menu',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do grupo (ex: Administradores, Secretaria, Financeiro)', max_length=100, unique=True, verbose_name='Nome do Grupo')),
                ('descricao', models.TextField(blank=True, help_text='Descrição do grupo e suas responsabilidades', verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, help_text='Grupos inativos não concedem permissões', verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('permissoes', models.ManyToManyField(blank=True, help_text='Menus que este grupo pode acessar', related_name='grupos', to='eventos.permissaomenu', verbose_name='Permissões')),
                ('usuarios', models.ManyToManyField(blank=True, help_text='Usuários que pertencem a este grupo', related_name='grupos_admin', to=settings.AUTH_USER_MODEL, verbose_name='Usuários')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['nome'],
            },
        ),
    ]
