# Generated by Django 4.2.11 on 2026-02-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0014_permissaomenu_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='evolution_api_instance',
            field=models.CharField(blank=True, help_text='Nome da instância configurada na Evolution API', max_length=100, verbose_name='Instância Evolution'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='evolution_api_key',
            field=models.CharField(blank=True, help_text='Chave de autenticação da API Evolution', max_length=200, verbose_name='Chave de API Evolution'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='evolution_api_url',
            field=models.URLField(blank=True, help_text='URL base da API Evolution (ex: https://api.evolution.com.br)', verbose_name='URL da API Evolution'),
        ),
    ]
