# Generated by Django 4.2.11 on 2026-02-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0015_configuracaosite_evolution_api_instance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='imagem_banner',
            field=models.ImageField(blank=True, help_text='Foto que substitui o fundo azul da seção de boas-vindas', null=True, upload_to='configuracoes/', verbose_name='Imagem do Banner (página inicial)'),
        ),
    ]
