# Generated by Django 4.2+

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0017_add_cor_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='cor_rodape',
            field=models.CharField(blank=True, default='#1a365d', help_text='Cor de fundo do rodapé (ex: #1a365d)', max_length=7, verbose_name='Cor do rodapé'),
        ),
    ]
