# Generated by Django 4.2+

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0018_add_cor_rodape'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='cor_header_pagina',
            field=models.CharField(blank=True, default='#1a365d', help_text='Cor da faixa de título das páginas (ex.: Meus Ingressos, Eventos, Sobre)', max_length=7, verbose_name='Cor do header das páginas'),
        ),
    ]
