# Generated by Django 4.2+

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0019_add_cor_header_pagina'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='webhook_eventos',
            field=models.URLField(blank=True, help_text='URL para notificar quando um evento é criado, atualizado ou excluído', null=True, verbose_name='Webhook de Eventos'),
        ),
    ]
