# Generated by Django 4.2+

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0020_add_webhook_eventos'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='mp_webhook_secret',
            field=models.CharField(
                blank=True,
                max_length=200,
                verbose_name='Webhook Secret (Mercado Pago)',
                help_text='Secret para validar assinatura dos webhooks (painel Mercado Pago > Webhooks > Configurar notificações)',
            ),
        ),
    ]
