# Generated by Django 4.2.11 on 2026-04-23 23:08

from django.db import migrations, models
import django.db.models.deletion
import eventos.models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0023_configuracaosite_mp_cartao_em_sandbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioInscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome interno para reutilização (ex: Retiro Adultos 2026)', max_length=150, verbose_name='Nome do Formulário')),
                ('descricao', models.TextField(blank=True, help_text='Descrição curta exibida para o admin ao selecionar o formulário', verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, help_text='Apenas formulários ativos aparecem na seleção de eventos', verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Formulário de Inscrição',
                'verbose_name_plural': 'Formulários de Inscrição',
                'ordering': ['-atualizado_em', 'nome'],
            },
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='mp_cartao_em_sandbox',
            field=models.BooleanField(default=False, help_text='Quando ativo: PIX usa sempre Produção (obrigatório para PIX). Cartão usa Sandbox para testar com cartões de teste, sem cobrança real. Deixe o ambiente geral em Produção.', verbose_name='Cartão em Sandbox (testes)'),
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='mp_webhook_secret',
            field=models.CharField(blank=True, help_text='Secret para validar assinatura dos webhooks (painel MP > Webhooks > Configurar notificações)', max_length=200, verbose_name='Webhook Secret (Mercado Pago)'),
        ),
        migrations.CreateModel(
            name='CampoFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição (menor = primeiro)', verbose_name='Ordem')),
                ('label', models.CharField(help_text='Texto exibido para o participante', max_length=200, verbose_name='Rótulo')),
                ('tipo', models.CharField(choices=[('texto_curto', 'Texto curto'), ('texto_longo', 'Texto longo'), ('numero', 'Número'), ('data', 'Data'), ('boolean', 'Sim/Não'), ('select_unico', 'Seleção única'), ('select_multiplo', 'Seleção múltipla'), ('email', 'E-mail'), ('telefone', 'Telefone'), ('cpf', 'CPF'), ('arquivo', 'Arquivo')], default='texto_curto', max_length=20, verbose_name='Tipo')),
                ('obrigatorio', models.BooleanField(default=False, verbose_name='Obrigatório')),
                ('placeholder', models.CharField(blank=True, help_text='Texto de apoio dentro do campo (opcional)', max_length=200, verbose_name='Placeholder')),
                ('help_text', models.CharField(blank=True, help_text='Texto exibido abaixo do campo', max_length=300, verbose_name='Texto de ajuda')),
                ('opcoes', models.JSONField(blank=True, default=list, help_text='Lista de opções para campos de seleção (apenas select_unico/select_multiplo)', verbose_name='Opções')),
                ('tamanho_max', models.PositiveIntegerField(blank=True, help_text='Tamanho máximo em caracteres (texto) ou em MB (arquivo). Opcional.', null=True, verbose_name='Tamanho máximo')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='eventos.formularioinscricao', verbose_name='Formulário')),
            ],
            options={
                'verbose_name': 'Campo de Formulário',
                'verbose_name_plural': 'Campos de Formulário',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='formulario_inscricao',
            field=models.ForeignKey(blank=True, help_text='Formulário opcional exibido durante a inscrição. Se vazio, o evento não coleta respostas extras.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='eventos.formularioinscricao', verbose_name='Formulário de Inscrição'),
        ),
        migrations.CreateModel(
            name='RespostaCampoInscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.JSONField(blank=True, default=dict, help_text='Valor escalar (texto, número, boolean, lista de opções).', verbose_name='Valor')),
                ('arquivo', models.FileField(blank=True, help_text='Usado apenas quando o campo é do tipo arquivo', null=True, upload_to=eventos.models._upload_path_resposta, verbose_name='Arquivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas', to='eventos.campoformulario', verbose_name='Campo')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='eventos.inscricao', verbose_name='Inscrição')),
            ],
            options={
                'verbose_name': 'Resposta de Inscrição',
                'verbose_name_plural': 'Respostas de Inscrição',
                'ordering': ['campo__ordem', 'campo_id'],
                'unique_together': {('inscricao', 'campo')},
            },
        ),
    ]
