# Generated by Django 4.2.27 on 2026-06-04 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0046_cobrancaitem_inscricao_set_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaosite',
            name='evolution_api_instance_loja',
            field=models.CharField(blank=True, help_text='Nome da instância usada para enviar recibos da loja/cantina. Reaproveita a URL base da Evolution acima.', max_length=100, verbose_name='Instância Evolution (Loja/Cantina)'),
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='mp_loja_pix_cpf_cnpj',
            field=models.CharField(blank=True, help_text='CPF ou CNPJ da igreja (só números) para pagamentos da loja/cantina sem cadastro do comprador.', max_length=18, verbose_name='CPF/CNPJ pagador PIX (loja)'),
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='mp_loja_pix_email',
            field=models.EmailField(blank=True, help_text='Usado no PIX/cartão da loja quando o cliente não se identifica. Vazio = e-mail de contato da igreja.', max_length=254, verbose_name='E-mail pagador PIX (loja)'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='permite_inscricao_adolescente',
            field=models.BooleanField(default=False, help_text='Quando ativo, quem se inscreve informa se é Adulto ou Adolescente (valor integral). Faixas do grupo valem só para acompanhantes.', verbose_name='Permite inscrição de adolescente'),
        ),
        migrations.CreateModel(
            name='Sorteio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, help_text='Nome opcional da sessão (ex.: Brindes do culto)', max_length=200, verbose_name='Título')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('em_andamento', 'Em andamento'), ('encerrado', 'Encerrado')], default='rascunho', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('encerrado_em', models.DateTimeField(blank=True, null=True, verbose_name='Encerrado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorteios_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorteios', to='eventos.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Sorteio',
                'verbose_name_plural': 'Sorteios',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='SorteioGanhador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodada', models.PositiveIntegerField(verbose_name='Rodada')),
                ('premio', models.CharField(blank=True, max_length=200, verbose_name='Prêmio')),
                ('sorteado_em', models.DateTimeField(auto_now_add=True, verbose_name='Sorteado em')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorteios_ganhos', to='eventos.inscricao', verbose_name='Inscrição')),
                ('sorteado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorteios_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Sorteado por')),
                ('sorteio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ganhadores', to='eventos.sorteio', verbose_name='Sorteio')),
            ],
            options={
                'verbose_name': 'Ganhador do sorteio',
                'verbose_name_plural': 'Ganhadores do sorteio',
                'ordering': ['rodada'],
                'unique_together': {('sorteio', 'inscricao')},
            },
        ),
        migrations.CreateModel(
            name='SorteioElegivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participa', models.BooleanField(default=True, verbose_name='Participa do sorteio')),
                ('observacao', models.CharField(blank=True, help_text='Ex.: Equipe mídia, pastor', max_length=255, verbose_name='Observação')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorteios_elegiveis', to='eventos.inscricao', verbose_name='Inscrição')),
                ('sorteio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elegiveis', to='eventos.sorteio', verbose_name='Sorteio')),
            ],
            options={
                'verbose_name': 'Elegível do sorteio',
                'verbose_name_plural': 'Elegíveis do sorteio',
                'ordering': ['inscricao__membro__nome'],
                'unique_together': {('sorteio', 'inscricao')},
            },
        ),
    ]
