# Generated by Django 4.2.27 on 2026-06-20 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0050_evento_checkin_abre_em'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobFila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(db_index=True, max_length=80)),
                ('fila', models.CharField(choices=[('critica', 'Critica (pagamentos/estoque)'), ('whatsapp', 'WhatsApp'), ('baixa', 'Baixa prioridade (webhooks/auditoria)')], db_index=True, default='baixa', max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('executando', 'Executando'), ('sucesso', 'Sucesso'), ('falha', 'Falha'), ('cancelado', 'Cancelado')], db_index=True, default='pendente', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('tentativas', models.PositiveIntegerField(default=0)),
                ('max_tentativas', models.PositiveIntegerField(default=5)),
                ('proxima_execucao_em', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ultima_execucao_em', models.DateTimeField(blank=True, null=True)),
                ('duracao_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('ultimo_erro', models.TextField(blank=True)),
                ('referencia_tipo', models.CharField(blank=True, db_index=True, max_length=80)),
                ('referencia_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('job_id', models.CharField(blank=True, max_length=80)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Job de Fila',
                'verbose_name_plural': 'Jobs de Fila',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AlterField(
            model_name='sorteioganhador',
            name='status',
            field=models.CharField(choices=[('confirmado', 'Confirmado'), ('ausente', 'Ausente')], default='confirmado', help_text='Ausente: não compareceu para retirar o prêmio (permanece fora do pool deste prêmio).', max_length=20, verbose_name='Status do prêmio'),
        ),
        migrations.CreateModel(
            name='WhatsappMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('inscricao_gratis', 'Inscricao gratuita'), ('inscricao_paga_pendente', 'Inscricao paga - pendente'), ('inscricao_paga_confirmada', 'Inscricao paga - confirmada'), ('inscricao_isenta_admin', 'Inscricao isenta (admin)'), ('reset_senha', 'Reset de senha'), ('cobranca_confirmada', 'Cobranca confirmada'), ('recibo_loja', 'Recibo loja'), ('lembrete_reserva_loja', 'Lembrete reserva loja')], db_index=True, max_length=40)),
                ('telefone', models.CharField(db_index=True, max_length=30)),
                ('mensagem_renderizada', models.TextField(blank=True)),
                ('instancia_override', models.CharField(blank=True, max_length=120)),
                ('api_key_override', models.CharField(blank=True, max_length=255)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp', to='eventos.jobfila')),
            ],
            options={
                'verbose_name': 'Mensagem WhatsApp',
                'verbose_name_plural': 'Mensagens WhatsApp',
                'ordering': ['-job__criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TentativaJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('terminou_em', models.DateTimeField(blank=True, null=True)),
                ('sucesso', models.BooleanField(default=False)),
                ('erro', models.TextField(blank=True)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas_log', to='eventos.jobfila')),
            ],
            options={
                'verbose_name': 'Tentativa de Job',
                'verbose_name_plural': 'Tentativas de Job',
                'ordering': ['-iniciado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='jobfila',
            index=models.Index(fields=['status', 'tipo'], name='eventos_job_status_2c31a2_idx'),
        ),
        migrations.AddIndex(
            model_name='jobfila',
            index=models.Index(fields=['fila', 'status'], name='eventos_job_fila_7e7eaa_idx'),
        ),
        migrations.AddIndex(
            model_name='jobfila',
            index=models.Index(fields=['proxima_execucao_em'], name='eventos_job_proxima_999728_idx'),
        ),
    ]
