"""CSP para Checkout Bricks / SDK Mercado Pago (iframes PCI + scripts) e Google Picker/OAuth."""

MP_CONTENT_SECURITY_POLICY = (
    "default-src 'self'; "
    "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://sdk.mercadopago.com "
    "https://*.mercadopago.com https://*.mercadopago.com.br https://*.mlstatic.com "
    "https://http2.mlstatic.com https://resources.mlstatic.com https://*.mercadolibre.com "
    "https://*.googleapis.com https://*.gstatic.com https://analytics.kbosolucoes.com.br "
    "https://accounts.google.com https://apis.google.com; "
    "script-src-elem 'self' 'unsafe-inline' https://sdk.mercadopago.com "
    "https://*.mercadopago.com https://*.mercadopago.com.br https://*.mlstatic.com "
    "https://http2.mlstatic.com https://resources.mlstatic.com https://*.mercadolibre.com "
    "https://analytics.kbosolucoes.com.br https://accounts.google.com https://apis.google.com "
    "https://*.googleapis.com https://*.gstatic.com; "
    "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com "
    "https://*.mercadopago.com https://*.mlstatic.com https://*.mercadolibre.com; "
    "img-src 'self' data: blob: https:; "
    "font-src 'self' data: https://fonts.gstatic.com https://*.mlstatic.com; "
    "connect-src 'self' https://api.mercadopago.com https://*.mercadopago.com "
    "https://*.mercadopago.com.br https://*.mercadolibre.com https://*.mlstatic.com "
    "https://http2.mlstatic.com https://analytics.kbosolucoes.com.br "
    "https://oauth2.googleapis.com https://www.googleapis.com https://accounts.google.com; "
    "frame-src 'self' https://*.mercadopago.com https://*.mercadopago.com.br "
    "https://www.mercadopago.com https://www.mercadopago.com.br "
    "https://http2.mlstatic.com https://resources.mlstatic.com "
    "https://*.mercadolibre.com https://*.mlstatic.com "
    "https://www.google.com https://maps.google.com https://*.google.com "
    "https://accounts.google.com https://docs.google.com; "
    "child-src 'self' blob: https://*.mercadopago.com https://www.mercadopago.com "
    "https://www.mercadopago.com.br https://*.mercadolibre.com https://*.mlstatic.com "
    "https://accounts.google.com; "
    "worker-src 'self' blob:; "
    "frame-ancestors 'none';"
)
