# Generated by Django 4.2.11 on 2026-04-25 00:31

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('pendente_pagamento', 'Pendente pagamento'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], db_index=True, default='rascunho', max_length=30, verbose_name='Status')),
                ('meio_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix_mp', 'PIX (Mercado Pago)'), ('cartao_mp', 'Cartão (Mercado Pago)')], default='dinheiro', max_length=20, verbose_name='Meio de pagamento')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('comprador_nome', models.CharField(blank=True, max_length=200, verbose_name='Comprador (balcão)')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas_loja', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('categoria', models.CharField(choices=[('cantina', 'Cantina'), ('loja', 'Loja')], db_index=True, max_length=20, verbose_name='Categoria')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['categoria', 'ativo'], name='loja_produt_categor_153f36_idx')],
            },
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço unitário')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_venda', to='loja.produto', verbose_name='Produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='loja.venda', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Item de venda',
                'verbose_name_plural': 'Itens de venda',
            },
        ),
        migrations.CreateModel(
            name='CobrancaLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=36, unique=True, verbose_name='Código')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], db_index=True, default='pendente', max_length=20, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('data_pagamento', models.DateTimeField(blank=True, null=True, verbose_name='Data do pagamento')),
                ('metodo_pagamento', models.CharField(blank=True, max_length=80, verbose_name='Método de pagamento')),
                ('referencia_externa', models.CharField(blank=True, max_length=100, verbose_name='Referência externa (MP)')),
                ('venda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cobranca_mp', to='loja.venda', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Cobrança (loja)',
                'verbose_name_plural': 'Cobranças (loja)',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['-data_criacao', 'status'], name='loja_venda_data_cr_a72066_idx'),
        ),
        migrations.AddIndex(
            model_name='cobrancaloja',
            index=models.Index(fields=['-data_criacao', 'status'], name='loja_cobran_data_cr_c45796_idx'),
        ),
    ]
