# Generated by Django 4.2.11 on 2026-04-25 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loja', '0004_produto_segmento_cantina'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True, help_text='Só a data; o limite da cota incide nesse dia.', verbose_name='Dia (culto)')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome (identificação)')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('status', models.CharField(choices=[('pendente', 'Pendente (só reserva)'), ('em_cobranca', 'Na fila (venda rascunho)'), ('pago', 'Pago'), ('cancelada', 'Cancelada')], db_index=True, default='pendente', max_length=20, verbose_name='Status')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Reserva (loja/cantina)',
                'verbose_name_plural': 'Reservas (loja/cantina)',
                'ordering': ['-data', '-data_criacao', 'id'],
            },
        ),
        migrations.RenameIndex(
            model_name='produto',
            new_name='loja_produt_categor_b2af34_idx',
            old_name='loja_prod_cat_seg_ativo',
        ),
        migrations.AddField(
            model_name='produto',
            name='aceita_reserva',
            field=models.BooleanField(db_index=True, default=False, help_text='Permite reservar por dia (culto) com limite na cota abaixo.', verbose_name='Aceita reserva'),
        ),
        migrations.AddField(
            model_name='produto',
            name='cota_reserva_diaria',
            field=models.PositiveIntegerField(blank=True, help_text='Ex.: 30 coxinhas fritas por culto. Deixe vazio para não limitar (ou desmarque “Aceita reserva”).', null=True, verbose_name='Cota de reservas (por dia)'),
        ),
        migrations.AddField(
            model_name='reservaloja',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas_cantina', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='reservaloja',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='loja.produto', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='reservaloja',
            name='venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_vinculadas', to='loja.venda', verbose_name='Venda (rascunho ou paga)'),
        ),
        migrations.AddIndex(
            model_name='reservaloja',
            index=models.Index(fields=['produto', 'data', 'status'], name='loja_reserv_produto_158986_idx'),
        ),
    ]
