# Generated by Django 4.2.11 on 2026-04-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_remove_produto_reserva_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaloja',
            name='em_estoque_empenhado',
            field=models.BooleanField(db_index=True, default=False, help_text='Se true, a quantidade já foi abatida do saldo de Produto.estoque ao reservar.', verbose_name='Empenho de estoque aplicado'),
        ),
    ]
