# Generated by Django 4.2.11 on 2026-04-27 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loja', '0008_retro_empenho_reservas_antigas'),
    ]

    operations = [
        migrations.CreateModel(
            name='LojaAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_evento', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data do evento')),
                ('tipo_evento', models.CharField(choices=[('produto_criado', 'Produto criado'), ('produto_atualizado', 'Produto atualizado'), ('produto_preco_alterado', 'Preço de produto alterado'), ('venda_criada', 'Venda criada'), ('venda_itens_alterados', 'Itens da venda alterados'), ('venda_pagamento_dinheiro', 'Venda paga em dinheiro'), ('venda_pagamento_mp', 'Venda paga no Mercado Pago'), ('venda_cancelada', 'Venda cancelada')], db_index=True, max_length=40, verbose_name='Tipo do evento')),
                ('detalhes', models.JSONField(blank=True, default=dict, verbose_name='Detalhes')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to='loja.produto', verbose_name='Produto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_loja_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to='loja.venda', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Log de auditoria da loja',
                'verbose_name_plural': 'Logs de auditoria da loja',
                'ordering': ['-data_evento', '-id'],
                'indexes': [models.Index(fields=['-data_evento', 'tipo_evento'], name='loja_lojaau_data_ev_e64d5d_idx'), models.Index(fields=['venda', '-data_evento'], name='loja_lojaau_venda_i_41ad78_idx'), models.Index(fields=['produto', '-data_evento'], name='loja_lojaau_produto_fd06e4_idx')],
            },
        ),
    ]
